{% set name                = "isoPropeller" %}
{% set version             = "1.8.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: git@github.com:PintolabMSSM/{{ name }}.git

build:
  number: 1
  noarch: generic

requirements:
  build:
    - perl=5.32.1
    - perl-bioperl
    - perl-getopt-long
    - perl-list-moreutils
    - samtools
    - bedtools
    - htslib
  run:
    - perl=5.32.1
    - perl-bioperl
    - perl-getopt-long
    - perl-list-moreutils
    - samtools
    - bedtools
    - htslib

test:
  commands:
    - isoPropeller -h

about:
  home: https://github.com/PintolabMSSM/{{ name }}/
  license: Attribution-NonCommercial 4.0 International
  license_family: CC
  summary: Code for isoPropeller isoform analysis.
