{% set name                = "isoPropeller" %}
{% set version             = "1.8.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: git@github.com:PintolabMSSM/{{ name }}.git

build:
  number: 2
  noarch: generic

requirements:
  build:
    - perl
  run:
    - perl
    - perl-bioperl
    - perl-getopt-long
    - perl-list-moreutils
    - perl

test:
  commands:
    - isoPropeller -h

about:
  home: https://github.com/PintolabMSSM/{{ name }}/
  license: Attribution-NonCommercial 4.0 International
  license_family: CC
  summary: Code for isoPropeller isoform analysis.
